- id: PLUMgrid-Gateway
  type: group
  role: [PLUMgrid-Gateway]
  tasks:
    - hiera
    - globals
    - netconfig
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel
